### ISSUE TITLE
Dataset used

### ISSUE THREAD

**Issue by msaad1311** [luckystarufo/MrCAE#2]
Hello. First off amazing work, however, I am struggling to get the dataset. Is it possible that you can share the google drive link to the datasets?

**Comment by luckystarufo** [comment]
Hello, for the toy datasets, the notebook scripts have already provided the way to obtain them. For others, I'm sorry I cannot provide it directly as data sets belong to third parties and we don't have the permission to distribute it. You should contact the ones who own them (eg. for JHU Turbulence data: http://turbulence.pha.jhu.edu/authtoken.aspx) and ask for a token to download.
